trigger:
  branches:
    include:
      - main

stages:
  - stage: CI
    displayName: "Build Services"
    jobs:
      - template: "pipelines/build.pipeline.yml"
        parameters:
          services:
            - Mateusz.Nadobnik.Service1
            - Mateusz.Nadobnik.Service2
            - Mateusz.Nadobnik.Service3
          containerRegistry: "container-registry"
