trigger:
  branches:
    include:
      - main

stages:
  - stage: CI
    displayName: "Build Services"
    jobs:
      - template: "pipelines/build.pipeline.yml"
        parameters:
          service: "Mateusz.Nadobnik.Service1"
          containerRegistry: "container-registry"

      - template: "pipelines/build.pipeline.yml"
        parameters:
          service: "Mateusz.Nadobnik.Service2"
          containerRegistry: "container-registry"

      - template: "pipelines/build.pipeline.yml"
        parameters:
          service: "Mateusz.Nadobnik.Service3"
          containerRegistry: "container-registry"
